### ISSUE TITLE
Undefined index: sic_codes 

### ISSUE THREAD

**Issue by privyreza** [JustSteveKing/companies-house-laravel#2]
Hello, thanks for working on this package. May you kindly assist. I am getting this error on Laravel 8 when i try to search company using company number

```Undefined index: sic_codes {"userId":10,"exception":"[object] (ErrorException(code: 0): Undefined index: sic_codes at /home/vpn/Desktop/projects/sucasa/vendor/juststeveking/companies-house-laravel/src/Data/Company.php:93)```

**Comment by JustSteveKing** [comment]
This "should" be fixed now, but I am in the process of planning of rewrite for v2 - let me know if it works for you, and I will increase the urgency going forward

**Comment by JustSteveKing** [comment]
@privyreza feel free to explore the 2.0 branch which is the upcoming release which has more features and is Laravel 8 only
